### ISSUE TITLE
Make CRUD API endpoints for adding new content from Admin dashboard

### ISSUE THREAD

**Issue by prank7** [AltCampus/exposureSystem#11]
BACKEND ONLY

- Add an endpoint that takes in all the params of `content` and saves it to DB
- Add an endpoint that shows all the contents
- Add an endpoint that shows a specific content
- Add an endpoint that deletes a specific content
- Add an endpoint that lets you update an existing content.

**Comment by BadBrahmin** [comment]
@AmanSharma4419 @Yjspoder PR opened. Please review and push further. 

Note: Admin CRUD needs auth.
