### ISSUE TITLE
Make React components for admin login and student signup and login pages

### ISSUE THREAD

**Issue by prank7** [AltCampus/exposureSystem#6]
REACT COMPONENTS ONLY

- Specify and document frontend guidelines
- Structure React app properly
- Make Student signup and login page
- Make Admin login page

**Comment by BadBrahmin** [comment]
@AmanSharma4419 @Yjspoder please review and pass further.

**Comment by prank7** [comment]
Looks good. @BadBrahmin @akhildhiman
